### ISSUE TITLE
Color palette

### ISSUE THREAD

**Issue by haveamission** [lordmir/landstalker_gfx#8]
Trying to make a new Landstalker style game and I was wondering if there was a way to extract the color palette from the game so I could have an idea of the colors used?

**Comment by lordmir** [comment]
Yes, I have made a change to the editor that will let you read and modify the palette data. You can also export the palette data as a CSV file.
These changes haven't been released yet, but they will be soon. If you are interested, I do have a dump of the hex values for all the palettes in the game.
